manifest: "manifest.tab"

# Annotations mode only if differential methylation is on. Therefore, only for autism cohort.
annotations:
  GRCh38:
    cpg_island: "/net/eichler/vol27/projects/autism_genome_assembly/nobackups/anno/regulatory/subsetted_beds/modified/hg38_cpgIslandExt_parsed.bed"
    sfari: "/net/eichler/vol27/projects/autism_genome_assembly/nobackups/anno/SFARI-Gene_genes_04-03-2023release_06-22-2023export.bed"
    genes: "/net/eichler/vol27/projects/autism_genome_assembly/nobackups/anno/GRCh38_genes-minimal.sorted.bed"
    go_desc: "/net/eichler/vol27/projects/autism_genome_assembly/nobackups/anno/goa_human_2023-06-13_simplified.bed"
    SV_genes: "sv-asd_all_inherited-info_20230601.sorted.bed"